### ISSUE TITLE
Support for WordPress multisite instalation

### ISSUE THREAD

**Issue by telmott** [wodby/wordpress-php#3]
Hi, is it possible to add support for a WordPress multisite installation?

Or if this image already support that, how can that be achieved.

Thank's in advance 😄

**Comment by csandanov** [comment]
Yes, it's possible. Achieved the same way as you would do it without docker

**Comment by telmott** [comment]
Hi @csandanov thanks for the quick reply 👍 .

But is it with environment variables in the .env file? I tried to create the variable WP_ALLOW_MULTISITE=true, but didn't work out.

 How can i access the wp-config.php?

If this is more like a docker support question, and completely out of scope, please let me know 😃.
Thank's

**Comment by csandanov** [comment]
Assuming you're using this image with [docker4wordpress](https://github.com/wodby/docker4wordpress) and have your codebase mounted, you should have access to `wp-config.php` from your host machine

**Comment by telmott** [comment]
@csandanov thanks a lot 👍 😄
