### ISSUE TITLE
Warning on entering WordPress PHP container via kubectl in Wodby env

### ISSUE THREAD

**Issue by pprishchepa** [wodby/wordpress-php#4]
Stack WordPress v5.3.0, Wodby env. Trying to enter php container and got this warning:
```
sh: /usr/local/include/wp-completion.bash: line 12: syntax error: unexpected "(" (expecting "fi")
```

**Comment by csandanov** [comment]
WP bash completion file misses shebang, the error doesn't happen with bash shell, fixed by replacing the default shell to bash in Wodby commands

**Comment by csandanov** [comment]
Also, it seems we added bash completion to `.shrc`, now fixed.

**Comment by sandykadam** [comment]
@pprishchepa can you please share your deployment file for k8s deployment with wodby image.
Thanks in advance.
